# Generated by Django 4.2.15 on 2024-11-18 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configurator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetWebProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platformName', models.CharField(blank=True, max_length=10000, null=True)),
                ('Profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='web_profiles', to='configurator.profile')),
                ('keyword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='web_keyword', to='configurator.keyword')),
            ],
        ),
        migrations.CreateModel(
            name='TargetWebProfileArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleTitle', models.TextField(blank=True, null=True)),
                ('articleDescription', models.TextField(blank=True, null=True)),
                ('originalThumbnail', models.URLField(blank=True, null=True)),
                ('articlePublishedAt', models.DateTimeField(blank=True, null=True)),
                ('originalArticleUrl', models.URLField(blank=True, null=True)),
                ('articleSentiment', models.CharField(blank=True, choices=[('positive', 'positive'), ('negative', 'negative'), ('neutral', 'neutral')], default='neutral', max_length=100, null=True)),
                ('targetWebProfile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='webcrawlers.targetwebprofile')),
            ],
        ),
    ]
