# Generated by Django 4.2.15 on 2024-11-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawlers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetwebprofilearticle',
            name='media',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='targetwebprofilearticle',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
