# Generated by Django 4.2.15 on 2024-12-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawlers', '0002_targetwebprofilearticle_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetwebprofilearticle',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='targetwebprofilearticle',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
