# Generated by Django 5.2.3 on 2025-09-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawlers', '0003_alter_targetwebprofilearticle_media_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='topicModeling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.JSONField()),
                ('images', models.JSONField()),
                ('urls', models.JSONField()),
                ('topic_title', models.CharField(blank=True, max_length=255, null=True)),
                ('topic_content', models.TextField(blank=True, null=True)),
                ('sentiment', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='targetwebprofile',
            name='topicModeling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='targetwebprofilearticle',
            name='frResult',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='targetwebprofilearticle',
            name='ocrResult',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='targetwebprofilearticle',
            index=models.Index(fields=['articlePublishedAt'], name='idx_article_published_at'),
        ),
        migrations.AddIndex(
            model_name='targetwebprofilearticle',
            index=models.Index(fields=['articleSentiment'], name='idx_article_sentiment'),
        ),
        migrations.AddIndex(
            model_name='targetwebprofilearticle',
            index=models.Index(fields=['targetWebProfile'], name='idx_article_target_profile'),
        ),
    ]
