version: "3.9"

services:
  db:
    image: postgres:16
    container_name: forsight-db
    restart: always
    environment:
      POSTGRES_DB: annotation
      POSTGRES_USER: staging
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - appnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U staging -d annotation || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  appnet:
    name: appnet

volumes:
  postgres_data:
