# Generated by Django 4.2.15 on 2024-11-18 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configurator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetXProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targetProfileXId', models.CharField(blank=True, max_length=200, null=True)),
                ('targetProfileName', models.CharField(blank=True, max_length=100, null=True)),
                ('targetProfileScreenName', models.CharField(blank=True, max_length=100, null=True)),
                ('isBlueTickVerified', models.BooleanField(default=False)),
                ('defaultProfile', models.BooleanField(default=False)),
                ('targetProfileCreatedAt', models.DateTimeField(blank=True, null=True)),
                ('targetProfileDescription', models.TextField(blank=True, null=True)),
                ('targetProfileDisplayUrl', models.CharField(blank=True, max_length=100, null=True)),
                ('targetProfileFastFollowersCount', models.IntegerField(blank=True, null=True)),
                ('targetProfileLink', models.CharField(blank=True, max_length=100, null=True)),
                ('targetProfileFavouritesCount', models.IntegerField(blank=True, null=True)),
                ('targetProfileFollowersCount', models.IntegerField(blank=True, null=True)),
                ('targetProfileFriendsCount', models.IntegerField(blank=True, null=True)),
                ('targetProfileGeographicalLocation', models.CharField(blank=True, max_length=100, null=True)),
                ('targetProfileMediaCount', models.IntegerField(blank=True, null=True)),
                ('targetProfileNormalFollowersCount', models.IntegerField(blank=True, null=True)),
                ('targetProfileStatusesCount', models.IntegerField(blank=True, null=True)),
                ('Keyword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_x_keywords', to='configurator.keyword')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_x_profiles', to='configurator.profile')),
            ],
        ),
        migrations.CreateModel(
            name='TargetXProfileTweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweetText', models.TextField(blank=True, null=True)),
                ('tweetViews', models.IntegerField(blank=True, null=True)),
                ('tweetKeyword', models.CharField(blank=True, max_length=500, null=True)),
                ('cleanTweetText', models.TextField(blank=True, null=True)),
                ('tweetReplies', models.IntegerField(blank=True, null=True)),
                ('tweetQuoteCount', models.IntegerField(blank=True, null=True)),
                ('tweetFavoriteCount', models.IntegerField(blank=True, null=True)),
                ('retweetCount', models.IntegerField(blank=True, null=True)),
                ('tweetBookmarkCount', models.IntegerField(blank=True, null=True)),
                ('tweetCreatedAt', models.DateTimeField(blank=True, null=True)),
                ('tweetImageLink', models.CharField(blank=True, max_length=100, null=True)),
                ('tweetImageData', models.TextField(blank=True, null=True)),
                ('tweetOriginalLink', models.CharField(blank=True, max_length=100, null=True)),
                ('tweetVideo', models.CharField(blank=True, max_length=1000, null=True)),
                ('tweetImage', models.CharField(blank=True, max_length=1000, null=True)),
                ('tweetSentiment', models.CharField(blank=True, choices=[('positive', 'positive'), ('negative', 'negative'), ('neutral', 'neutral')], default='neutral', max_length=100, null=True)),
                ('targetXProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xcrawlers.targetxprofile')),
            ],
        ),
    ]
