# Generated by Django 5.2.3 on 2025-09-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xcrawlers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetxprofiletweet',
            name='frResult',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='targetxprofiletweet',
            name='ocrResult',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='targetxprofiletweet',
            index=models.Index(fields=['tweetCreatedAt'], name='xcrawlers_t_tweetCr_bb7ca8_idx'),
        ),
        migrations.AddIndex(
            model_name='targetxprofiletweet',
            index=models.Index(fields=['tweetSentiment'], name='xcrawlers_t_tweetSe_511769_idx'),
        ),
        migrations.AddIndex(
            model_name='targetxprofiletweet',
            index=models.Index(fields=['targetXProfile'], name='xcrawlers_t_targetX_44b233_idx'),
        ),
    ]
