# Generated by Django 4.2.15 on 2024-11-18 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configurator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetYoutubeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channelName', models.CharField(blank=True, max_length=100, null=True)),
                ('channelSubscribersCount', models.FloatField(default=0)),
                ('channelDescription', models.TextField(blank=True, null=True)),
                ('channelUrl', models.URLField(blank=True, null=True)),
                ('channelVideoCount', models.IntegerField(default=0)),
                ('channelViewCount', models.IntegerField(default=0)),
                ('channelPublishedAt', models.DateTimeField(blank=True, null=True)),
                ('channelCountry', models.CharField(blank=True, max_length=100, null=True)),
                ('keyword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='youtube_profiles', to='configurator.keyword')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='youtube_profiles', to='configurator.profile')),
            ],
        ),
        migrations.CreateModel(
            name='TargetYoutubeProfileVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoTitle', models.TextField(blank=True, null=True)),
                ('videoDuration', models.IntegerField(blank=True, default=0, null=True)),
                ('videoViewCount', models.IntegerField(default=0)),
                ('originalVideoUrl', models.URLField(blank=True, null=True)),
                ('originalVideoTumbnailUrl', models.URLField(blank=True, null=True)),
                ('videoPublishedAt', models.DateTimeField(blank=True, null=True)),
                ('videoLink', models.CharField(blank=True, max_length=300, null=True)),
                ('videoThumbnail', models.CharField(blank=True, max_length=300, null=True)),
                ('videoSentiment', models.CharField(blank=True, choices=[('positive', 'positive'), ('negative', 'negative'), ('neutral', 'neutral')], default='neutral', max_length=100, null=True)),
                ('targetYoutubeProfile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='youtubecrawlers.targetyoutubeprofile')),
            ],
        ),
    ]
