# Generated by Django 4.2.15 on 2024-12-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubecrawlers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetyoutubeprofilevideo',
            name='videoLink',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='targetyoutubeprofilevideo',
            name='videoThumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
