# Generated by Django 5.2.3 on 2025-09-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubecrawlers', '0002_alter_targetyoutubeprofilevideo_videolink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetyoutubeprofilevideo',
            name='frVideoResult',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='targetyoutubeprofilevideo',
            name='srVideoResult',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='targetyoutubeprofilevideo',
            name='sttVideoResult',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='targetyoutubeprofilevideo',
            name='videoCommentsCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='targetyoutubeprofilevideo',
            name='videoLikesCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='targetyoutubeprofilevideo',
            name='videoTranscription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='targetyoutubeprofilevideo',
            name='videoViewCount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='targetyoutubeprofilevideo',
            index=models.Index(fields=['videoPublishedAt'], name='youtubecraw_videoPu_0d0d4b_idx'),
        ),
        migrations.AddIndex(
            model_name='targetyoutubeprofilevideo',
            index=models.Index(fields=['videoSentiment'], name='youtubecraw_videoSe_e51f19_idx'),
        ),
        migrations.AddIndex(
            model_name='targetyoutubeprofilevideo',
            index=models.Index(fields=['targetYoutubeProfile'], name='youtubecraw_targetY_cfba12_idx'),
        ),
    ]
