# Generated by Django 4.2.15 on 2024-11-18 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('X', 'X'), ('Facebook', 'Facebook'), ('Web', 'Web'), ('YouTube', 'YouTube')], max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='platformLogo/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileName', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('profileUrl', models.URLField(unique=True)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('dataCount', models.IntegerField(default=0)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='configurator.platform')),
                ('user', models.ManyToManyField(related_name='user_profile', to='account.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('xDataCount', models.IntegerField(default=0)),
                ('youtubeDataCount', models.IntegerField(default=0)),
                ('facebookDataCount', models.IntegerField(default=0)),
                ('webDataCount', models.IntegerField(default=0)),
                ('dataCount', models.IntegerField(default=0)),
                ('platforms', models.ManyToManyField(related_name='platform_list', to='configurator.platform')),
                ('user', models.ManyToManyField(related_name='profile', to='account.userprofile')),
            ],
        ),
    ]
