# Generated by Django 5.2.3 on 2025-09-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileName', models.TextField(blank=True, null=True)),
                ('profilePlatform', models.TextField(blank=True, null=True)),
                ('startedAt', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=20)),
                ('finishedAt', models.DateTimeField(blank=True, null=True)),
                ('recordsCrawled', models.IntegerField(default=0)),
                ('errorMessage', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchedularLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
                ('profile_count', models.IntegerField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='keyword',
            name='suspended',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='topicModeling',
            field=models.BooleanField(default=False),
        ),
    ]
